import React from 'react';
import { View, FolderOpen, Folders } from '@carbon/react/icons';
import { IconButton } from '@carbon/react';
import LeapAILabel, { LeapAILabelContent, LeapAILabelActions } from './LeapAILabel.jsx';

export default {
  title: 'Components/LeapAILabel',
  component: LeapAILabel,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component: 'An AI indicator badge with a toggletip popover, used to mark AI-generated or AI-assisted content with optional revert and action buttons.',
      },
    },
  },
  argTypes: {
    aiText: { control: 'text' },
    kind: { control: 'select', options: ['default', 'inline'] },
    size: { control: 'select', options: ['mini', '2xs', 'xs', 'sm', 'md', 'lg', 'xl'] },
    align: {
      control: 'select',
      options: ['top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'right'],
    },
    revertActive: { control: 'boolean' },
    onRevertClick: { action: 'revert clicked' },
  },
};

export const Default = {
  args: {
    size: 'xs',
    children: (
      <LeapAILabelContent>
        <p><strong>AI-assisted</strong></p>
        <p>This content was generated with the help of an AI model trained on LeapChange data.</p>
      </LeapAILabelContent>
    ),
  },
};

export const AllSizes = {
  render: () => (
    <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', flexWrap: 'wrap' }}>
      {['mini', '2xs', 'xs', 'sm', 'md', 'lg', 'xl'].map((size) => (
        <LeapAILabel key={size} size={size}>
          <LeapAILabelContent>
            <p>Size: <strong>{size}</strong></p>
          </LeapAILabelContent>
        </LeapAILabel>
      ))}
    </div>
  ),
};

export const Inline = {
  render: () => (
    <p style={{ fontSize: '0.875rem', color: '#525252' }}>
      This risk assessment was{' '}
      <LeapAILabel kind="inline" textLabel="generated by AI" size="sm">
        <LeapAILabelContent>
          <p><strong>AI-generated content</strong></p>
          <p>Confidence: 92%. Based on 340 historical data points.</p>
        </LeapAILabelContent>
        <LeapAILabelActions>
          <IconButton kind="ghost" label="View sources" size="sm">
            <View />
          </IconButton>
          <IconButton kind="ghost" label="Open folder" size="sm">
            <FolderOpen />
          </IconButton>
        </LeapAILabelActions>
      </LeapAILabel>{' '}
      and should be reviewed before sharing.
    </p>
  ),
};

export const WithActions = {
  render: () => (
    <LeapAILabel size="sm">
      <LeapAILabelContent>
        <p><strong>AI-assisted analysis</strong></p>
        <p>Model: LeapChange Insights v2. Confidence: 87%.</p>
      </LeapAILabelContent>
      <LeapAILabelActions>
        <IconButton kind="ghost" label="View details" size="sm">
          <View />
        </IconButton>
        <IconButton kind="ghost" label="Open in folder" size="sm">
          <FolderOpen />
        </IconButton>
        <IconButton kind="ghost" label="All versions" size="sm">
          <Folders />
        </IconButton>
      </LeapAILabelActions>
    </LeapAILabel>
  ),
};

export const Revert = {
  args: {
    revertActive: true,
    revertLabel: 'Revert to AI input',
  },
};
